name:                convex-pentagonal-tilings
version:             0.1.0.0
github:              "githubuser/convex-pentagonal-tilings"
license:             BSD3
author:              "Nikolaj von Holck"
maintainer:          "example@example.com"
copyright:           "2020 Nikolaj von Holck"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/convex-pentagonal-tilings#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  convex-pentagonal-tilings-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - convex-pentagonal-tilings

tests:
  convex-pentagonal-tilings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - convex-pentagonal-tilings
