name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: mstksg/setup-stack@v2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: stack-${{ hashFiles('stack.yaml.lock') }}

    - name: Build
      run: |
        stack --no-terminal build --fast --pedantic

    - name: Test
      run: |
        stack --no-terminal test --pedantic
